import { Sparkles } from "lucide-react"
import { cn } from "@/lib/utils"

interface AIGeneratedTagProps {
  className?: string
}

export function AIGeneratedTag({ className }: AIGeneratedTagProps) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full bg-gradient-to-r from-purple-500/10 to-blue-500/10 px-2.5 py-0.5 text-xs font-medium text-primary border border-purple-200/20 shadow-sm ml-2 whitespace-nowrap",
        className,
      )}
    >
      <Sparkles className="h-3 w-3 text-purple-500" />
      <span>generated by first-move-generative-AI</span>
    </span>
  )
}

