/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as ResetpassDealerImport } from './routes/resetpass-dealer'
import { Route as ResetpassImport } from './routes/resetpass'
import { Route as ForgotpassDealerImport } from './routes/forgotpass-dealer'
import { Route as ForgotpassImport } from './routes/forgotpass'
import { Route as DealerSignupImport } from './routes/dealer-signup'
import { Route as DealerSigninImport } from './routes/dealer-signin'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ResetpassDealerRoute = ResetpassDealerImport.update({
  id: '/resetpass-dealer',
  path: '/resetpass-dealer',
  getParentRoute: () => rootRoute,
} as any)

const ResetpassRoute = ResetpassImport.update({
  id: '/resetpass',
  path: '/resetpass',
  getParentRoute: () => rootRoute,
} as any)

const ForgotpassDealerRoute = ForgotpassDealerImport.update({
  id: '/forgotpass-dealer',
  path: '/forgotpass-dealer',
  getParentRoute: () => rootRoute,
} as any)

const ForgotpassRoute = ForgotpassImport.update({
  id: '/forgotpass',
  path: '/forgotpass',
  getParentRoute: () => rootRoute,
} as any)

const DealerSignupRoute = DealerSignupImport.update({
  id: '/dealer-signup',
  path: '/dealer-signup',
  getParentRoute: () => rootRoute,
} as any)

const DealerSigninRoute = DealerSigninImport.update({
  id: '/dealer-signin',
  path: '/dealer-signin',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dealer-signin': {
      id: '/dealer-signin'
      path: '/dealer-signin'
      fullPath: '/dealer-signin'
      preLoaderRoute: typeof DealerSigninImport
      parentRoute: typeof rootRoute
    }
    '/dealer-signup': {
      id: '/dealer-signup'
      path: '/dealer-signup'
      fullPath: '/dealer-signup'
      preLoaderRoute: typeof DealerSignupImport
      parentRoute: typeof rootRoute
    }
    '/forgotpass': {
      id: '/forgotpass'
      path: '/forgotpass'
      fullPath: '/forgotpass'
      preLoaderRoute: typeof ForgotpassImport
      parentRoute: typeof rootRoute
    }
    '/forgotpass-dealer': {
      id: '/forgotpass-dealer'
      path: '/forgotpass-dealer'
      fullPath: '/forgotpass-dealer'
      preLoaderRoute: typeof ForgotpassDealerImport
      parentRoute: typeof rootRoute
    }
    '/resetpass': {
      id: '/resetpass'
      path: '/resetpass'
      fullPath: '/resetpass'
      preLoaderRoute: typeof ResetpassImport
      parentRoute: typeof rootRoute
    }
    '/resetpass-dealer': {
      id: '/resetpass-dealer'
      path: '/resetpass-dealer'
      fullPath: '/resetpass-dealer'
      preLoaderRoute: typeof ResetpassDealerImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-signin': typeof DealerSigninRoute
  '/dealer-signup': typeof DealerSignupRoute
  '/forgotpass': typeof ForgotpassRoute
  '/forgotpass-dealer': typeof ForgotpassDealerRoute
  '/resetpass': typeof ResetpassRoute
  '/resetpass-dealer': typeof ResetpassDealerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-signin': typeof DealerSigninRoute
  '/dealer-signup': typeof DealerSignupRoute
  '/forgotpass': typeof ForgotpassRoute
  '/forgotpass-dealer': typeof ForgotpassDealerRoute
  '/resetpass': typeof ResetpassRoute
  '/resetpass-dealer': typeof ResetpassDealerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-signin': typeof DealerSigninRoute
  '/dealer-signup': typeof DealerSignupRoute
  '/forgotpass': typeof ForgotpassRoute
  '/forgotpass-dealer': typeof ForgotpassDealerRoute
  '/resetpass': typeof ResetpassRoute
  '/resetpass-dealer': typeof ResetpassDealerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dealer-signin'
    | '/dealer-signup'
    | '/forgotpass'
    | '/forgotpass-dealer'
    | '/resetpass'
    | '/resetpass-dealer'
    | '/signin'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dealer-signin'
    | '/dealer-signup'
    | '/forgotpass'
    | '/forgotpass-dealer'
    | '/resetpass'
    | '/resetpass-dealer'
    | '/signin'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dealer-signin'
    | '/dealer-signup'
    | '/forgotpass'
    | '/forgotpass-dealer'
    | '/resetpass'
    | '/resetpass-dealer'
    | '/signin'
    | '/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DealerSigninRoute: typeof DealerSigninRoute
  DealerSignupRoute: typeof DealerSignupRoute
  ForgotpassRoute: typeof ForgotpassRoute
  ForgotpassDealerRoute: typeof ForgotpassDealerRoute
  ResetpassRoute: typeof ResetpassRoute
  ResetpassDealerRoute: typeof ResetpassDealerRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DealerSigninRoute: DealerSigninRoute,
  DealerSignupRoute: DealerSignupRoute,
  ForgotpassRoute: ForgotpassRoute,
  ForgotpassDealerRoute: ForgotpassDealerRoute,
  ResetpassRoute: ResetpassRoute,
  ResetpassDealerRoute: ResetpassDealerRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/dealer-signin",
        "/dealer-signup",
        "/forgotpass",
        "/forgotpass-dealer",
        "/resetpass",
        "/resetpass-dealer",
        "/signin",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/dealer-signin": {
      "filePath": "dealer-signin.tsx"
    },
    "/dealer-signup": {
      "filePath": "dealer-signup.tsx"
    },
    "/forgotpass": {
      "filePath": "forgotpass.tsx"
    },
    "/forgotpass-dealer": {
      "filePath": "forgotpass-dealer.tsx"
    },
    "/resetpass": {
      "filePath": "resetpass.tsx"
    },
    "/resetpass-dealer": {
      "filePath": "resetpass-dealer.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
